# version: '3.8'

# services:
#   jenkins:
#     image: jenkins/jenkins:lts
#     container_name: jenkins1
#     restart: unless-stopped
#     ports:
#       - "8080:8080" # Expose Jenkins on port 8080
#       - "50000:50000" # Required for agent communication
#     volumes:
#       - jenkins_home:/var/jenkins_home # Persistent data storage
#       - /var/run/docker.sock:/var/run/docker.sock 
#     environment:
#       JAVA_OPTS: "-Djenkins.install.runSetupWizard=false" # Optional: skip setup wizard if preconfigured

# volumes:
#   jenkins_home:
#     driver: local

version: '3'
services:
  jenkins:
    build: .
    # image: jenkins-docker:lts
    container_name: jenkins1
    user: root
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins_home: