default_connection_name = "myconnection"

[connections.myconnection]
account = "POOGGWP-EQA42460"
user = "testsf"
password = "Gre@tness123"
database = "PRACTICE"
schema = "PUBLIC"
warehouse = "COMPUTE_WH"
role = "ACCOUNTADMIN"